channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.8.0
  - numpy=1.26.0
  - pip=23.3
  - python=3.11.5
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - scikit-learn=1.2.2
  - scipy=1.11.3
  - torchaudio=2.1.1
  - torchvision=0.16.1
  - pip:
      - captum==0.6.0
      - opencv-contrib-python==4.8.1.78
      - torchio==0.19.2
