channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pip
  - python=3.11
  - pytorch
  - pytorch-cuda=11
  - scikit-learn
  - scipy
  - torchaudio
  - torchvision
  - pip:
      - captum
      - opencv-contrib-python
      - torchio
